sudo: required
dist: trusty

language: rust
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
addons:
  apt:
    packages:
      - build-essential
      - libavcodec-dev
      - libavdevice-dev
      - libavfilter-dev
      - libavformat-dev
      - libavresample-dev
      - libavutil-dev
      - libswresample-dev
      - libswscale-dev
script:
  # Current Travis Ubuntu version uses libav which doesn't come with libswresample
  - 'cargo build --verbose --no-default-features --features "avcodec avfilter avformat avresample swscale"'
  - 'cargo test  --verbose --no-default-features --features "avcodec avfilter avformat avresample swscale"'
